sdk:
  - 3.12.2

stages:
  - analyze:
      - group:
          - analyze
  - build:
      - command: dart run build_runner build --fail-on-severe --delete-conflicting-outputs
  - unit_test:
      - command: dart run build_runner test --fail-on-severe --delete-conflicting-outputs -- -P ci -j1
