include: package:lints/recommended.yaml

analyzer:
  # language:
  #   strict-casts: true
  #   strict-inference: true
  #   strict-raw-types: true
  errors:
    # deprecated_member_use: warning
    todo: ignore
    uri_does_not_exist: info
    uri_has_not_been_generated: info
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_dynamic_calls
    - avoid_escaping_inner_quotes
    - avoid_print
    - avoid_void_async
    - directives_ordering
    - prefer_single_quotes
    - unnecessary_final
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_raw_strings
