name: angular_workspace
description: AngularDart workspace.
environment:
  sdk: ^3.8.3

dev_dependencies:
  lints: ^6.1.0

workspace:
  - _tests
  - angular
  - angular_ast
  - angular_compiler
  - angular_forms
  - angular_router
  - angular_test
  - examples/hello_world
  - tests
