name: angular_workspace
description: AngularDart workspace.
environment:
  sdk: ^3.7.3

dev_dependencies:
  lints: ^5.1.1

  # global tracking
  analyzer: 7.4.5
  build: 2.5.0
  build_daemon: 4.0.4
  build_modules: 5.0.11
  build_resolvers: 2.5.0
  build_runner: 2.5.0
  build_test: 3.0.0
  build_web_compilers: 4.1.5
  code_builder: 4.10.1
  dart_style: 3.1.0
  mockito: 5.4.6

workspace:
  - _tests
  - angular
  - angular_ast
  - angular_compiler
  - angular_forms
  - angular_router
  - angular_test
  - examples/hello_world
  - tests
