name: angular_workspace
description: AngularDart workspace.
environment:
  sdk: ^2.19.6

dependencies:
  angular: 7.0.2
  angular_ast: 2.0.1
  angular_compiler: 2.0.2
  angular_forms: 4.0.1
  angular_router: 3.0.1
  angular_test: 4.0.1

dev_dependencies:
  lints: ^2.0.1

dependency_overrides:
  angular:
    path: angular
  angular_ast:
    path: angular_ast
  angular_compiler:
    path: angular_compiler
  angular_forms:
    path: angular_forms
  angular_router:
    path: angular_router
  angular_test:
    path: angular_test
