sdk:
  - 3.4.4

stages:
  - analyze:
      - group:
          - analyze
  - build:
      - command: dart run build_runner build --fail-on-severe
  - unit_test:
      - command: dart run build_runner test --fail-on-severe -- -P ci -j1
