name: angular_test
description: Testing runner and library for AngularDart
repository: https://github.com/angulardart/angular
version: 4.0.1

environment:
  sdk: 2.16.2

dependencies:
  angular: ^7.0.2
  collection: ^1.17.0
  meta: ">=1.9.1 <1.10.0"

dev_dependencies:
  build_runner: ">=2.2.0 <2.2.1"
  build_test: ^2.1.5
  build_web_compilers: ^3.2.3
  lints: ^1.0.1
  test: ">=1.21.4 <1.21.5"

dependency_overrides:
  angular:
    path: ../angular
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
