sdk:
  - 3.0.7

stages:
  - build:
      - command: dart run build_runner build --fail-on-severe
  - unit_test:
      - command: dart test -P vm
      - command: dart run build_runner test --fail-on-severe -- -P browser
