name: _tests
description: Tests for AngularDart.

environment:
  sdk: ^3.7.3

resolution: workspace

dependencies:
  angular: ^8.0.0
  angular_compiler: ^3.0.0
  angular_test: ^5.0.0
  build: ^2.4.2
  build_resolvers: ^2.4.4
  build_test: ^2.2.3
  collection: ^1.19.1
  glob: ^2.1.3
  logging: ^1.3.0
  test: ^1.26.3

dev_dependencies:
  analyzer: ^7.3.0
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.2
  js: ^0.7.2
  lints: ^5.1.1
  package_config: ^2.2.0
  source_gen: ^2.0.0
  term_glyph: ^1.2.2
