name: angular
description: >-
  Fast and productive web framework by Google.
  Separate, but similar to the JavaScript framework with a similar name.
version: 7.1.0
repository: https://github.com/angulardart/angular

environment:
  sdk: ^3.3.4

dependencies:
  angular_compiler: ^2.1.0
  build: ^2.4.1
  built_collection: ^5.1.1
  built_value: ^8.12.4
  collection: ^1.18.0
  intl: ^0.19.0
  js: ^0.7.1
  lints: ^4.0.0
  meta: ^1.16.0
  stream_transform: ^2.1.1

dependency_overrides:
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
