name: angular
description: >-
  Fast and productive web framework by Google.
  Separate, but similar to the JavaScript framework with a similar name.
version: 7.1.0
repository: https://github.com/angulardart/angular

environment:
  sdk: ^2.19.6

dependencies:
  angular_compiler: ^2.1.0
  build: ^2.3.1
  built_collection: ^5.1.1
  built_value: ^8.8.0
  collection: ^1.18.0
  intl: ^0.18.1
  js: ^0.6.7
  lints: ^2.0.1
  meta: 1.9.1

dependency_overrides:
  angular_ast:
    path: ../angular_ast
  angular_compiler:
    path: ../angular_compiler
