name: angular
description: >-
  Fast and productive web framework by Google.
  Separate, but similar to the JavaScript framework with a similar name.
version: 7.1.0
repository: https://github.com/angulardart/angular

environment:
  sdk: ^3.6.2

resolution: workspace

dependencies:
  angular_compiler: ^2.1.0
  build: ^2.4.1
  built_collection: ^5.1.1
  built_value: ^8.12.4
  collection: ^1.19.1
  intl: ^0.20.2
  js: ^0.7.1
  meta: ^1.18.1
  stream_transform: ^2.1.1

dev_dependencies:
  lints: ^5.0.0
